//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18408.
// 
#pragma warning disable 1591

namespace DMarysSoft.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioSoap", Namespace="http://tempuri.org/")]
    public partial class Servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoIdyProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoIdySucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerConListaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerRangoFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoClientesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicio() {
            this.Url = global::DMarysSoft.Properties.Settings.Default.DMarysSoft_localhost_Servicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarSucursalesCompletedEventHandler GuardarSucursalesCompleted;
        
        /// <remarks/>
        public event EditarSucursalesCompletedEventHandler EditarSucursalesCompleted;
        
        /// <remarks/>
        public event EliminarSucursalesCompletedEventHandler EliminarSucursalesCompleted;
        
        /// <remarks/>
        public event ObtenerSucursalesCompletedEventHandler ObtenerSucursalesCompleted;
        
        /// <remarks/>
        public event ListadoSucursalCompletedEventHandler ListadoSucursalCompleted;
        
        /// <remarks/>
        public event GuardarProveedoresCompletedEventHandler GuardarProveedoresCompleted;
        
        /// <remarks/>
        public event EditarProveedoresCompletedEventHandler EditarProveedoresCompleted;
        
        /// <remarks/>
        public event EliminarProveedoresCompletedEventHandler EliminarProveedoresCompleted;
        
        /// <remarks/>
        public event ObtenerProveedoresCompletedEventHandler ObtenerProveedoresCompleted;
        
        /// <remarks/>
        public event ListadoProveedoresCompletedEventHandler ListadoProveedoresCompleted;
        
        /// <remarks/>
        public event GuardarProductosCompletedEventHandler GuardarProductosCompleted;
        
        /// <remarks/>
        public event EditarProductosCompletedEventHandler EditarProductosCompleted;
        
        /// <remarks/>
        public event EliminarProductosCompletedEventHandler EliminarProductosCompleted;
        
        /// <remarks/>
        public event ObtenerProductosCompletedEventHandler ObtenerProductosCompleted;
        
        /// <remarks/>
        public event ListadoProductosCompletedEventHandler ListadoProductosCompleted;
        
        /// <remarks/>
        public event ListadoIdyProveedoresCompletedEventHandler ListadoIdyProveedoresCompleted;
        
        /// <remarks/>
        public event ListadoIdySucursalesCompletedEventHandler ListadoIdySucursalesCompleted;
        
        /// <remarks/>
        public event ObtenerConListaCompletedEventHandler ObtenerConListaCompleted;
        
        /// <remarks/>
        public event GuardarVentasCompletedEventHandler GuardarVentasCompleted;
        
        /// <remarks/>
        public event EditarVentasCompletedEventHandler EditarVentasCompleted;
        
        /// <remarks/>
        public event EliminarVentasCompletedEventHandler EliminarVentasCompleted;
        
        /// <remarks/>
        public event ObtenerVentasCompletedEventHandler ObtenerVentasCompleted;
        
        /// <remarks/>
        public event ListadoVentasCompletedEventHandler ListadoVentasCompleted;
        
        /// <remarks/>
        public event ObtenerRangoFechaCompletedEventHandler ObtenerRangoFechaCompleted;
        
        /// <remarks/>
        public event GuardarClientesCompletedEventHandler GuardarClientesCompleted;
        
        /// <remarks/>
        public event EditarClientesCompletedEventHandler EditarClientesCompleted;
        
        /// <remarks/>
        public event EliminarClientesCompletedEventHandler EliminarClientesCompleted;
        
        /// <remarks/>
        public event ObtenerClientesCompletedEventHandler ObtenerClientesCompleted;
        
        /// <remarks/>
        public event ListadoClientesCompletedEventHandler ListadoClientesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarSucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarSucursales(SucursalesClase s) {
            this.Invoke("GuardarSucursales", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void GuardarSucursalesAsync(SucursalesClase s) {
            this.GuardarSucursalesAsync(s, null);
        }
        
        /// <remarks/>
        public void GuardarSucursalesAsync(SucursalesClase s, object userState) {
            if ((this.GuardarSucursalesOperationCompleted == null)) {
                this.GuardarSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarSucursalesOperationCompleted);
            }
            this.InvokeAsync("GuardarSucursales", new object[] {
                        s}, this.GuardarSucursalesOperationCompleted, userState);
        }
        
        private void OnGuardarSucursalesOperationCompleted(object arg) {
            if ((this.GuardarSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarSucursalesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarSucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarSucursales(SucursalesClase s) {
            this.Invoke("EditarSucursales", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void EditarSucursalesAsync(SucursalesClase s) {
            this.EditarSucursalesAsync(s, null);
        }
        
        /// <remarks/>
        public void EditarSucursalesAsync(SucursalesClase s, object userState) {
            if ((this.EditarSucursalesOperationCompleted == null)) {
                this.EditarSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarSucursalesOperationCompleted);
            }
            this.InvokeAsync("EditarSucursales", new object[] {
                        s}, this.EditarSucursalesOperationCompleted, userState);
        }
        
        private void OnEditarSucursalesOperationCompleted(object arg) {
            if ((this.EditarSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarSucursalesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarSucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarSucursales(int id) {
            this.Invoke("EliminarSucursales", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarSucursalesAsync(int id) {
            this.EliminarSucursalesAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarSucursalesAsync(int id, object userState) {
            if ((this.EliminarSucursalesOperationCompleted == null)) {
                this.EliminarSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarSucursalesOperationCompleted);
            }
            this.InvokeAsync("EliminarSucursales", new object[] {
                        id}, this.EliminarSucursalesOperationCompleted, userState);
        }
        
        private void OnEliminarSucursalesOperationCompleted(object arg) {
            if ((this.EliminarSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarSucursalesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerSucursales(int id) {
            object[] results = this.Invoke("ObtenerSucursales", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSucursalesAsync(int id) {
            this.ObtenerSucursalesAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerSucursalesAsync(int id, object userState) {
            if ((this.ObtenerSucursalesOperationCompleted == null)) {
                this.ObtenerSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSucursalesOperationCompleted);
            }
            this.InvokeAsync("ObtenerSucursales", new object[] {
                        id}, this.ObtenerSucursalesOperationCompleted, userState);
        }
        
        private void OnObtenerSucursalesOperationCompleted(object arg) {
            if ((this.ObtenerSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSucursalesCompleted(this, new ObtenerSucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SucursalesClase[] ListadoSucursal() {
            object[] results = this.Invoke("ListadoSucursal", new object[0]);
            return ((SucursalesClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoSucursalAsync() {
            this.ListadoSucursalAsync(null);
        }
        
        /// <remarks/>
        public void ListadoSucursalAsync(object userState) {
            if ((this.ListadoSucursalOperationCompleted == null)) {
                this.ListadoSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoSucursalOperationCompleted);
            }
            this.InvokeAsync("ListadoSucursal", new object[0], this.ListadoSucursalOperationCompleted, userState);
        }
        
        private void OnListadoSucursalOperationCompleted(object arg) {
            if ((this.ListadoSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoSucursalCompleted(this, new ListadoSucursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarProveedores(ProveedoresClase p) {
            this.Invoke("GuardarProveedores", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void GuardarProveedoresAsync(ProveedoresClase p) {
            this.GuardarProveedoresAsync(p, null);
        }
        
        /// <remarks/>
        public void GuardarProveedoresAsync(ProveedoresClase p, object userState) {
            if ((this.GuardarProveedoresOperationCompleted == null)) {
                this.GuardarProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarProveedoresOperationCompleted);
            }
            this.InvokeAsync("GuardarProveedores", new object[] {
                        p}, this.GuardarProveedoresOperationCompleted, userState);
        }
        
        private void OnGuardarProveedoresOperationCompleted(object arg) {
            if ((this.GuardarProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarProveedoresCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarProveedores(ProveedoresClase p) {
            this.Invoke("EditarProveedores", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void EditarProveedoresAsync(ProveedoresClase p) {
            this.EditarProveedoresAsync(p, null);
        }
        
        /// <remarks/>
        public void EditarProveedoresAsync(ProveedoresClase p, object userState) {
            if ((this.EditarProveedoresOperationCompleted == null)) {
                this.EditarProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarProveedoresOperationCompleted);
            }
            this.InvokeAsync("EditarProveedores", new object[] {
                        p}, this.EditarProveedoresOperationCompleted, userState);
        }
        
        private void OnEditarProveedoresOperationCompleted(object arg) {
            if ((this.EditarProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarProveedoresCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarProveedores(int id) {
            this.Invoke("EliminarProveedores", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarProveedoresAsync(int id) {
            this.EliminarProveedoresAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarProveedoresAsync(int id, object userState) {
            if ((this.EliminarProveedoresOperationCompleted == null)) {
                this.EliminarProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProveedoresOperationCompleted);
            }
            this.InvokeAsync("EliminarProveedores", new object[] {
                        id}, this.EliminarProveedoresOperationCompleted, userState);
        }
        
        private void OnEliminarProveedoresOperationCompleted(object arg) {
            if ((this.EliminarProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProveedoresCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerProveedores(int id) {
            object[] results = this.Invoke("ObtenerProveedores", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerProveedoresAsync(int id) {
            this.ObtenerProveedoresAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerProveedoresAsync(int id, object userState) {
            if ((this.ObtenerProveedoresOperationCompleted == null)) {
                this.ObtenerProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerProveedoresOperationCompleted);
            }
            this.InvokeAsync("ObtenerProveedores", new object[] {
                        id}, this.ObtenerProveedoresOperationCompleted, userState);
        }
        
        private void OnObtenerProveedoresOperationCompleted(object arg) {
            if ((this.ObtenerProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerProveedoresCompleted(this, new ObtenerProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProveedoresClase[] ListadoProveedores() {
            object[] results = this.Invoke("ListadoProveedores", new object[0]);
            return ((ProveedoresClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoProveedoresAsync() {
            this.ListadoProveedoresAsync(null);
        }
        
        /// <remarks/>
        public void ListadoProveedoresAsync(object userState) {
            if ((this.ListadoProveedoresOperationCompleted == null)) {
                this.ListadoProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoProveedoresOperationCompleted);
            }
            this.InvokeAsync("ListadoProveedores", new object[0], this.ListadoProveedoresOperationCompleted, userState);
        }
        
        private void OnListadoProveedoresOperationCompleted(object arg) {
            if ((this.ListadoProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoProveedoresCompleted(this, new ListadoProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarProductos(ProductosClase p) {
            this.Invoke("GuardarProductos", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void GuardarProductosAsync(ProductosClase p) {
            this.GuardarProductosAsync(p, null);
        }
        
        /// <remarks/>
        public void GuardarProductosAsync(ProductosClase p, object userState) {
            if ((this.GuardarProductosOperationCompleted == null)) {
                this.GuardarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarProductosOperationCompleted);
            }
            this.InvokeAsync("GuardarProductos", new object[] {
                        p}, this.GuardarProductosOperationCompleted, userState);
        }
        
        private void OnGuardarProductosOperationCompleted(object arg) {
            if ((this.GuardarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarProductosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarProductos(ProductosClase p) {
            this.Invoke("EditarProductos", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void EditarProductosAsync(ProductosClase p) {
            this.EditarProductosAsync(p, null);
        }
        
        /// <remarks/>
        public void EditarProductosAsync(ProductosClase p, object userState) {
            if ((this.EditarProductosOperationCompleted == null)) {
                this.EditarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarProductosOperationCompleted);
            }
            this.InvokeAsync("EditarProductos", new object[] {
                        p}, this.EditarProductosOperationCompleted, userState);
        }
        
        private void OnEditarProductosOperationCompleted(object arg) {
            if ((this.EditarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarProductosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarProductos(string id) {
            this.Invoke("EliminarProductos", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarProductosAsync(string id) {
            this.EliminarProductosAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarProductosAsync(string id, object userState) {
            if ((this.EliminarProductosOperationCompleted == null)) {
                this.EliminarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProductosOperationCompleted);
            }
            this.InvokeAsync("EliminarProductos", new object[] {
                        id}, this.EliminarProductosOperationCompleted, userState);
        }
        
        private void OnEliminarProductosOperationCompleted(object arg) {
            if ((this.EliminarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProductosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerProductos(string id) {
            object[] results = this.Invoke("ObtenerProductos", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerProductosAsync(string id) {
            this.ObtenerProductosAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerProductosAsync(string id, object userState) {
            if ((this.ObtenerProductosOperationCompleted == null)) {
                this.ObtenerProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerProductosOperationCompleted);
            }
            this.InvokeAsync("ObtenerProductos", new object[] {
                        id}, this.ObtenerProductosOperationCompleted, userState);
        }
        
        private void OnObtenerProductosOperationCompleted(object arg) {
            if ((this.ObtenerProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerProductosCompleted(this, new ObtenerProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosClase[] ListadoProductos() {
            object[] results = this.Invoke("ListadoProductos", new object[0]);
            return ((ProductosClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoProductosAsync() {
            this.ListadoProductosAsync(null);
        }
        
        /// <remarks/>
        public void ListadoProductosAsync(object userState) {
            if ((this.ListadoProductosOperationCompleted == null)) {
                this.ListadoProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoProductosOperationCompleted);
            }
            this.InvokeAsync("ListadoProductos", new object[0], this.ListadoProductosOperationCompleted, userState);
        }
        
        private void OnListadoProductosOperationCompleted(object arg) {
            if ((this.ListadoProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoProductosCompleted(this, new ListadoProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoIdyProveedores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProveedoresClase[] ListadoIdyProveedores() {
            object[] results = this.Invoke("ListadoIdyProveedores", new object[0]);
            return ((ProveedoresClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoIdyProveedoresAsync() {
            this.ListadoIdyProveedoresAsync(null);
        }
        
        /// <remarks/>
        public void ListadoIdyProveedoresAsync(object userState) {
            if ((this.ListadoIdyProveedoresOperationCompleted == null)) {
                this.ListadoIdyProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoIdyProveedoresOperationCompleted);
            }
            this.InvokeAsync("ListadoIdyProveedores", new object[0], this.ListadoIdyProveedoresOperationCompleted, userState);
        }
        
        private void OnListadoIdyProveedoresOperationCompleted(object arg) {
            if ((this.ListadoIdyProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoIdyProveedoresCompleted(this, new ListadoIdyProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoIdySucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SucursalesClase[] ListadoIdySucursales() {
            object[] results = this.Invoke("ListadoIdySucursales", new object[0]);
            return ((SucursalesClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoIdySucursalesAsync() {
            this.ListadoIdySucursalesAsync(null);
        }
        
        /// <remarks/>
        public void ListadoIdySucursalesAsync(object userState) {
            if ((this.ListadoIdySucursalesOperationCompleted == null)) {
                this.ListadoIdySucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoIdySucursalesOperationCompleted);
            }
            this.InvokeAsync("ListadoIdySucursales", new object[0], this.ListadoIdySucursalesOperationCompleted, userState);
        }
        
        private void OnListadoIdySucursalesOperationCompleted(object arg) {
            if ((this.ListadoIdySucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoIdySucursalesCompleted(this, new ListadoIdySucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerConLista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosClase[] ObtenerConLista(string id) {
            object[] results = this.Invoke("ObtenerConLista", new object[] {
                        id});
            return ((ProductosClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerConListaAsync(string id) {
            this.ObtenerConListaAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerConListaAsync(string id, object userState) {
            if ((this.ObtenerConListaOperationCompleted == null)) {
                this.ObtenerConListaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerConListaOperationCompleted);
            }
            this.InvokeAsync("ObtenerConLista", new object[] {
                        id}, this.ObtenerConListaOperationCompleted, userState);
        }
        
        private void OnObtenerConListaOperationCompleted(object arg) {
            if ((this.ObtenerConListaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerConListaCompleted(this, new ObtenerConListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarVentas(VentasClase s) {
            this.Invoke("GuardarVentas", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void GuardarVentasAsync(VentasClase s) {
            this.GuardarVentasAsync(s, null);
        }
        
        /// <remarks/>
        public void GuardarVentasAsync(VentasClase s, object userState) {
            if ((this.GuardarVentasOperationCompleted == null)) {
                this.GuardarVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarVentasOperationCompleted);
            }
            this.InvokeAsync("GuardarVentas", new object[] {
                        s}, this.GuardarVentasOperationCompleted, userState);
        }
        
        private void OnGuardarVentasOperationCompleted(object arg) {
            if ((this.GuardarVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarVentasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarVentas(VentasClase s) {
            this.Invoke("EditarVentas", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void EditarVentasAsync(VentasClase s) {
            this.EditarVentasAsync(s, null);
        }
        
        /// <remarks/>
        public void EditarVentasAsync(VentasClase s, object userState) {
            if ((this.EditarVentasOperationCompleted == null)) {
                this.EditarVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarVentasOperationCompleted);
            }
            this.InvokeAsync("EditarVentas", new object[] {
                        s}, this.EditarVentasOperationCompleted, userState);
        }
        
        private void OnEditarVentasOperationCompleted(object arg) {
            if ((this.EditarVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarVentasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarVentas(int id) {
            this.Invoke("EliminarVentas", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarVentasAsync(int id) {
            this.EliminarVentasAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarVentasAsync(int id, object userState) {
            if ((this.EliminarVentasOperationCompleted == null)) {
                this.EliminarVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarVentasOperationCompleted);
            }
            this.InvokeAsync("EliminarVentas", new object[] {
                        id}, this.EliminarVentasOperationCompleted, userState);
        }
        
        private void OnEliminarVentasOperationCompleted(object arg) {
            if ((this.EliminarVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarVentasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerVentas(int id) {
            object[] results = this.Invoke("ObtenerVentas", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerVentasAsync(int id) {
            this.ObtenerVentasAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerVentasAsync(int id, object userState) {
            if ((this.ObtenerVentasOperationCompleted == null)) {
                this.ObtenerVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerVentasOperationCompleted);
            }
            this.InvokeAsync("ObtenerVentas", new object[] {
                        id}, this.ObtenerVentasOperationCompleted, userState);
        }
        
        private void OnObtenerVentasOperationCompleted(object arg) {
            if ((this.ObtenerVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerVentasCompleted(this, new ObtenerVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VentasClase[] ListadoVentas() {
            object[] results = this.Invoke("ListadoVentas", new object[0]);
            return ((VentasClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoVentasAsync() {
            this.ListadoVentasAsync(null);
        }
        
        /// <remarks/>
        public void ListadoVentasAsync(object userState) {
            if ((this.ListadoVentasOperationCompleted == null)) {
                this.ListadoVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoVentasOperationCompleted);
            }
            this.InvokeAsync("ListadoVentas", new object[0], this.ListadoVentasOperationCompleted, userState);
        }
        
        private void OnListadoVentasOperationCompleted(object arg) {
            if ((this.ListadoVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoVentasCompleted(this, new ListadoVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerRangoFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VentasClase[] ObtenerRangoFecha(string fecha1, string fecha2) {
            object[] results = this.Invoke("ObtenerRangoFecha", new object[] {
                        fecha1,
                        fecha2});
            return ((VentasClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerRangoFechaAsync(string fecha1, string fecha2) {
            this.ObtenerRangoFechaAsync(fecha1, fecha2, null);
        }
        
        /// <remarks/>
        public void ObtenerRangoFechaAsync(string fecha1, string fecha2, object userState) {
            if ((this.ObtenerRangoFechaOperationCompleted == null)) {
                this.ObtenerRangoFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRangoFechaOperationCompleted);
            }
            this.InvokeAsync("ObtenerRangoFecha", new object[] {
                        fecha1,
                        fecha2}, this.ObtenerRangoFechaOperationCompleted, userState);
        }
        
        private void OnObtenerRangoFechaOperationCompleted(object arg) {
            if ((this.ObtenerRangoFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerRangoFechaCompleted(this, new ObtenerRangoFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarClientes(ClientesClase c) {
            this.Invoke("GuardarClientes", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void GuardarClientesAsync(ClientesClase c) {
            this.GuardarClientesAsync(c, null);
        }
        
        /// <remarks/>
        public void GuardarClientesAsync(ClientesClase c, object userState) {
            if ((this.GuardarClientesOperationCompleted == null)) {
                this.GuardarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarClientesOperationCompleted);
            }
            this.InvokeAsync("GuardarClientes", new object[] {
                        c}, this.GuardarClientesOperationCompleted, userState);
        }
        
        private void OnGuardarClientesOperationCompleted(object arg) {
            if ((this.GuardarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarClientesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarClientes(ClientesClase c) {
            this.Invoke("EditarClientes", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void EditarClientesAsync(ClientesClase c) {
            this.EditarClientesAsync(c, null);
        }
        
        /// <remarks/>
        public void EditarClientesAsync(ClientesClase c, object userState) {
            if ((this.EditarClientesOperationCompleted == null)) {
                this.EditarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarClientesOperationCompleted);
            }
            this.InvokeAsync("EditarClientes", new object[] {
                        c}, this.EditarClientesOperationCompleted, userState);
        }
        
        private void OnEditarClientesOperationCompleted(object arg) {
            if ((this.EditarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarClientesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarClientes(int id) {
            this.Invoke("EliminarClientes", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarClientesAsync(int id) {
            this.EliminarClientesAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarClientesAsync(int id, object userState) {
            if ((this.EliminarClientesOperationCompleted == null)) {
                this.EliminarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarClientesOperationCompleted);
            }
            this.InvokeAsync("EliminarClientes", new object[] {
                        id}, this.EliminarClientesOperationCompleted, userState);
        }
        
        private void OnEliminarClientesOperationCompleted(object arg) {
            if ((this.EliminarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarClientesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerClientes(int id) {
            object[] results = this.Invoke("ObtenerClientes", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClientesAsync(int id) {
            this.ObtenerClientesAsync(id, null);
        }
        
        /// <remarks/>
        public void ObtenerClientesAsync(int id, object userState) {
            if ((this.ObtenerClientesOperationCompleted == null)) {
                this.ObtenerClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClientesOperationCompleted);
            }
            this.InvokeAsync("ObtenerClientes", new object[] {
                        id}, this.ObtenerClientesOperationCompleted, userState);
        }
        
        private void OnObtenerClientesOperationCompleted(object arg) {
            if ((this.ObtenerClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClientesCompleted(this, new ObtenerClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientesClase[] ListadoClientes() {
            object[] results = this.Invoke("ListadoClientes", new object[0]);
            return ((ClientesClase[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoClientesAsync() {
            this.ListadoClientesAsync(null);
        }
        
        /// <remarks/>
        public void ListadoClientesAsync(object userState) {
            if ((this.ListadoClientesOperationCompleted == null)) {
                this.ListadoClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoClientesOperationCompleted);
            }
            this.InvokeAsync("ListadoClientes", new object[0], this.ListadoClientesOperationCompleted, userState);
        }
        
        private void OnListadoClientesOperationCompleted(object arg) {
            if ((this.ListadoClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoClientesCompleted(this, new ListadoClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SucursalesClase {
        
        private int idSucursalField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        /// <comentarios/>
        public int IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientesClase {
        
        private int idClienteField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        /// <comentarios/>
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VentasClase {
        
        private int idSucursalField;
        
        private double cambioField;
        
        private double efectivoField;
        
        private double subtotalField;
        
        private double ivaField;
        
        private double totalField;
        
        private string fechaField;
        
        private string clienteField;
        
        private int idUsuarioField;
        
        private int idVentaField;
        
        /// <comentarios/>
        public int IdSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public double Cambio {
            get {
                return this.cambioField;
            }
            set {
                this.cambioField = value;
            }
        }
        
        /// <comentarios/>
        public double Efectivo {
            get {
                return this.efectivoField;
            }
            set {
                this.efectivoField = value;
            }
        }
        
        /// <comentarios/>
        public double Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
            }
        }
        
        /// <comentarios/>
        public double Iva {
            get {
                return this.ivaField;
            }
            set {
                this.ivaField = value;
            }
        }
        
        /// <comentarios/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <comentarios/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <comentarios/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public int IdVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductosClase {
        
        private int idProveedorField;
        
        private int idSucursalField;
        
        private string descripcionField;
        
        private int stockField;
        
        private double precioField;
        
        private string tallaField;
        
        private string modeloField;
        
        private string colorField;
        
        private string marcaField;
        
        private string estiloField;
        
        private string sexoField;
        
        private double descuentoField;
        
        private System.DateTime fechaIngresoField;
        
        private string codigoProductoField;
        
        private int idProveedorField1;
        
        private int idSucursalField1;
        
        private string descripcionField1;
        
        private int stockField1;
        
        private double precioField1;
        
        private string tallaField1;
        
        private string modeloField1;
        
        private string colorField1;
        
        private string marcaField1;
        
        private string estiloField1;
        
        private string sexoField1;
        
        private double descuentoField1;
        
        private System.DateTime fechaIngresoField1;
        
        /// <comentarios/>
        public int idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                this.idProveedorField = value;
            }
        }
        
        /// <comentarios/>
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                this.idSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
            }
        }
        
        /// <comentarios/>
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        public string talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
            }
        }
        
        /// <comentarios/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <comentarios/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <comentarios/>
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <comentarios/>
        public string estilo {
            get {
                return this.estiloField;
            }
            set {
                this.estiloField = value;
            }
        }
        
        /// <comentarios/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        public double descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
        
        /// <comentarios/>
        public string CodigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
            }
        }
        
        /// <comentarios/>
        public int IdProveedor {
            get {
                return this.idProveedorField1;
            }
            set {
                this.idProveedorField1 = value;
            }
        }
        
        /// <comentarios/>
        public int IdSucursal {
            get {
                return this.idSucursalField1;
            }
            set {
                this.idSucursalField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField1;
            }
            set {
                this.descripcionField1 = value;
            }
        }
        
        /// <comentarios/>
        public int Stock {
            get {
                return this.stockField1;
            }
            set {
                this.stockField1 = value;
            }
        }
        
        /// <comentarios/>
        public double Precio {
            get {
                return this.precioField1;
            }
            set {
                this.precioField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Talla {
            get {
                return this.tallaField1;
            }
            set {
                this.tallaField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Modelo {
            get {
                return this.modeloField1;
            }
            set {
                this.modeloField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Color {
            get {
                return this.colorField1;
            }
            set {
                this.colorField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Marca {
            get {
                return this.marcaField1;
            }
            set {
                this.marcaField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Estilo {
            get {
                return this.estiloField1;
            }
            set {
                this.estiloField1 = value;
            }
        }
        
        /// <comentarios/>
        public string Sexo {
            get {
                return this.sexoField1;
            }
            set {
                this.sexoField1 = value;
            }
        }
        
        /// <comentarios/>
        public double Descuento {
            get {
                return this.descuentoField1;
            }
            set {
                this.descuentoField1 = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaIngreso {
            get {
                return this.fechaIngresoField1;
            }
            set {
                this.fechaIngresoField1 = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProveedoresClase {
        
        private int idproveedorField;
        
        private string nombreempresaField;
        
        private string direccionempresaField;
        
        private string telefonoempresaField;
        
        /// <comentarios/>
        public int Idproveedor {
            get {
                return this.idproveedorField;
            }
            set {
                this.idproveedorField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombreempresa {
            get {
                return this.nombreempresaField;
            }
            set {
                this.nombreempresaField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccionempresa {
            get {
                return this.direccionempresaField;
            }
            set {
                this.direccionempresaField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefonoempresa {
            get {
                return this.telefonoempresaField;
            }
            set {
                this.telefonoempresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GuardarSucursalesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditarSucursalesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EliminarSucursalesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerSucursalesCompletedEventHandler(object sender, ObtenerSucursalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSucursalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSucursalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoSucursalCompletedEventHandler(object sender, ListadoSucursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SucursalesClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SucursalesClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GuardarProveedoresCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditarProveedoresCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EliminarProveedoresCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerProveedoresCompletedEventHandler(object sender, ObtenerProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoProveedoresCompletedEventHandler(object sender, ListadoProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProveedoresClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProveedoresClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GuardarProductosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditarProductosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EliminarProductosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerProductosCompletedEventHandler(object sender, ObtenerProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoProductosCompletedEventHandler(object sender, ListadoProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoIdyProveedoresCompletedEventHandler(object sender, ListadoIdyProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoIdyProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoIdyProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProveedoresClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProveedoresClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoIdySucursalesCompletedEventHandler(object sender, ListadoIdySucursalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoIdySucursalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoIdySucursalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SucursalesClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SucursalesClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerConListaCompletedEventHandler(object sender, ObtenerConListaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerConListaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerConListaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GuardarVentasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditarVentasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EliminarVentasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerVentasCompletedEventHandler(object sender, ObtenerVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoVentasCompletedEventHandler(object sender, ListadoVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VentasClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VentasClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerRangoFechaCompletedEventHandler(object sender, ObtenerRangoFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerRangoFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerRangoFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VentasClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VentasClase[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GuardarClientesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditarClientesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EliminarClientesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerClientesCompletedEventHandler(object sender, ObtenerClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ListadoClientesCompletedEventHandler(object sender, ListadoClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientesClase[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientesClase[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591