using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;

namespace DMarysSoftWEB
{
    public partial class Formulario_web110 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            //gvEliminarUsuarios.AutoGenerateSelectButton=true;
            gvEliminarUsuarios.AutoGenerateDeleteButton = true;
        }

        protected void GridView_RowDeleted(object sender, GridViewDeletedEventArgs e)
        {
            // Esto es para borrar un usuario.
            try
            {
                string usuario = gvEliminarUsuarios.SelectedRow.Cells[2].Text.ToString();
                Membership.DeleteUser(usuario, true);
            }catch(Exception ex){
                lblSeleccionado.Text = "Debe seleccionar un Usuario para eliminar!";
                //Server.ClearError();
            }


            /* Esto es para desactivar usuario solamente!
            MembershipUser mu = Membership.GetUser(usuario); // el nombre del usuario a inhabilitar.             
            mu.IsApproved = false;
            Membership.UpdateUser(mu); */

        }

        protected void gvEliminarUsuarios_SelectedIndexChanged(object sender, EventArgs e)
        {
            lblSeleccionado.Text = gvEliminarUsuarios.SelectedRow.Cells[2].Text.ToString();
        }
    }
}